apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: user
type: Opaque
stringData:
  DB_PASSWORD: "userpass"
  JWT_SECRET: "your-secret-key-change-in-production-use-base64-encoded-random-string"
