apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: user
spec:
  type: ClusterIP  # Internal only, accessed via API Gateway
  selector:
    app: user
  ports:
  - port: 8080
    targetPort: 8080
