apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: kamilbabayev/demo-bank:account
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: "postgres-account.infra.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "accountservice"
        - name: DB_PASSWORD
          value: "accountpass"
        - name: DB_NAME
          value: "accountdb"
        - name: KAFKA_BROKERS
          value: "kafka.infra.svc.cluster.local:9092"
        - name: REDIS_URL
          value: "redis://redis.redis.svc.cluster.local:6379"
        - name: JWT_SECRET
          value: "your-secret-key-change-in-production"
