apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: account
spec:
  type: ClusterIP  # Internal only, accessed via API Gateway
  selector:
    app: account
  ports:
  - port: 8080
    targetPort: 8080
